services:
  - type: web
    name: mod-sales
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: ADMIN_PASSWORD_HASH
        sync: false
      - key: TOKEN_SECRET
        sync: false
      - key: NODE_ENV
        value: production
