name = "mod-sales"
type = "javascript"
pages_build_output_dir = ".next"

account_id = "e816fe66309b031e719021172de64028"

[[d1_databases]]
binding = "DB"
database_name = "mod_sales"
database_id = "2965d474-14dc-4f0e-840a-e38918ea668a"

[env.production]
routes = [
  { pattern = "freenull.com", zone_name = "freenull.com" },
  { pattern = "*.freenull.com", zone_name = "freenull.com" }
]

[build]
command = "npm run build:cloudflare"
